apiVersion: apps/v1
kind: Deployment
metadata:
  name: project3-api-1
  labels:
    name: project3-api-1
spec:
  replicas: 1
  selector:
    matchLabels:
      service: project3-api-1
  template:
    metadata:
      labels:
        service: project3-api-1
    spec:
      containers:
        - name: project3-api-1
          image: 077552042909.dkr.ecr.us-east-1.amazonaws.com/project3:8
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: "/readiness_check"
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
